/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The statically visible surface of an ESM module: every exported name
 * (including `default` and `export * as ns` names) plus the specifiers of
 * bare `export * from` statements. The building block for resolving
 * star-forwarded names: walk the star sources' files with this, then pass
 * the found provenance to `exportsTap` as `starResolutions`.
 */
export interface EsmExportsInfo {
  names: Array<string>
  starSources: Array<string>
}

export declare function esmModuleExports(input: string): EsmExportsInfo

/**
 * The generic "exports tap" behind declarative patches, for every patch
 * entry of one module in a single call (one parse, at most one codegen):
 * each entry's patch function is handed the module's live bindings as
 * get/set accessors. The module is parsed once and every requested name
 * validated against its statically visible exports — a missing export
 * throws (the version-drift alarm). Bindings that are already reassignable
 * locals cost only the appended snippet; bindings that need restructuring
 * (`export const`, anonymous `export default`, re-exports, import-backed
 * locals) trigger an AST rewrite and `code`/`map` come back non-null. In
 * CJS mode (`cjs = true`) accessors go through `module.exports`, no
 * validation or rewrite happens and `input` is ignored — pass an empty
 * string. `registry` picks patch delivery: false emits a static import of
 * each entry's `patchFrom` (build time); true looks patches up in the
 * `Symbol.for("wrap-esm-lambda.patches")` global registry the runtime
 * shell preloads (no injected import/require at all). `filename` names the
 * module in the rewrite source map; `upstreamMap` chains an
 * already-applied transform's map through the rewrite.
 */
export declare function exportsTap(input: string, entries: Array<TapEntryInput>, cjs: boolean, registry: boolean, filename?: string | undefined | null, upstreamMap?: string | undefined | null, starResolutions?: Array<TapStarResolution> | undefined | null): TapResult

/**
 * Buffer-input variant of `exportsTap`, for the runtime hook path where
 * `registerHooks`' `nextLoad` already provides the source as UTF-8 bytes:
 * the Buffer crosses napi zero-copy, so validating a module's exports never
 * converts the whole source UTF-16 -> UTF-8. On the fast path (`code ==
 * null`) the source is never decoded at all — the caller appends `snippets`
 * bytes to the original buffer. On the rewrite path the regenerated module
 * comes back as a string (Node compiles from UTF-16 either way, so a string
 * costs the same single conversion). In CJS mode `input` is ignored — pass
 * an empty buffer. Throws if `input` is not valid UTF-8.
 */
export declare function exportsTapFromBuffer(input: Buffer, entries: Array<TapEntryInput>, cjs: boolean, registry: boolean, filename?: string | undefined | null, upstreamMap?: string | undefined | null, starResolutions?: Array<TapStarResolution> | undefined | null): TapResult

/**
 * Whether the source contains ESM module syntax (`import`/`export`
 * statements or `import.meta`) — the question Node's own format detection
 * answers for a `.js` file with no `"type"` field, and the fallback core's
 * CJS-or-ESM decision uses at build time when no explicit format is
 * available. A source that does not parse as ESM reports `false`.
 */
export declare function hasModuleSyntax(input: string): boolean

/**
 * Resolve a module specifier from a directory, the way an `import` (or an
 * ESM `export * from`) would: full Node/bundler resolution via
 * [oxc_resolver](https://docs.rs/oxc_resolver) — `node_modules` walk,
 * `"exports"` maps under the `node`/`import` conditions, `"module"` before
 * `"main"` for map-less packages (the ESM tree is what a star re-export
 * forwards), symlink-real paths (pnpm layouts included). This is what lets
 * core's star-graph walk follow `export * from "pkg"` with a **bare**
 * specifier: the walk needs the file behind the specifier to learn which
 * names it provides, while the emitted shadow export keeps importing from
 * the original specifier — resolution informs the transform, it never
 * lands in the output. Returns null when the specifier does not resolve;
 * the caller keeps its loud unresolved-star error.
 */
export declare function resolveModule(specifier: string, fromDir: string): string | null

/**
 * The version of the transform contract this addon implements: the emitted
 * snippet shapes plus the `TapEntryInput` / `TapResult` surfaces core depends
 * on. Bumped whenever one of those changes in a way core has to match.
 *
 * Core's package range cannot express this on its own. The addon is an
 * optional dependency resolved on the consumer's machine, so a core that was
 * installed with one addon can end up loaded next to another — and a silently
 * mismatched tap emits code that looks right and patches nothing. Core asks
 * for this number at bind time and treats a mismatch the same way it treats
 * an addon that will not load at all.
 */
export declare function tapContractVersion(): number

/**
 * One patch entry's inputs to the exports tap — mirrors the JS config entry.
 * `aliasIndex` keeps the injected import alias unique when several entries
 * patch the same module in import delivery.
 */
export interface TapEntryInput {
  bindings: Array<string>
  patchName: string
  patchFrom: string
  aliasIndex: number
}

/**
 * Result of `exportsTap` for one module (all entries at once):
 * - `code == null` — the append-only fast path: every requested binding was
 *   already a reassignable local. Append `snippets` after the untouched
 *   source (a byte-buffer caller never decodes it).
 * - `code != null` — the module needed restructuring (a `const` export, an
 *   anonymous default, a re-export or import-backed list export) and was
 *   regenerated from its AST; `map` is the v3 source map of that rewrite
 *   (already chained through `upstreamMap` when one was given). Append
 *   `snippets` after `code`.
 */
export interface TapResult {
  snippets: string
  code?: string
  map?: string
}

/**
 * A resolution for a name forwarded by a bare `export * from`: `binding`
 * is (transitively) provided by the star source `source`. Produced by the
 * caller's star-graph walk over `esmModuleExports`; the tap then reroutes
 * the name through an append-only shadow export (explicit named exports
 * shadow `export *` for the same name — no rewrite needed).
 */
export interface TapStarResolution {
  binding: string
  source: string
}
