/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function installHooks(): void

export declare function transformLambda(input: string, handler: string, wrapper: string): string

export declare function transformLambdaWithMap(input: string, handler: string, wrapper: string, filename: string): string

/**
 * Returns the transformed code and the raw v3 source map JSON separately, so a
 * caller can compose the map with an upstream `.ts` -> `.js` map (e.g. from
 * `tsc`) before attaching it.
 */
export declare function transformLambdaWithMapObject(input: string, handler: string, wrapper: string, filename: string): TransformResult

export interface TransformResult {
  code: string
  map?: string
}
